/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  SearchResult,
  SearchSearchRetrieveParams,
  SearchSuggestionResponse,
  SearchSuggestionRetrieveParams,
} from ".././models";

import { customInstance } from ".././mutator/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const searchSearchRetrieve = (
  params?: SearchSearchRetrieveParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<SearchResult>(
    { url: `/search/search/`, method: "GET", params, signal },
    options
  );
};

export const getSearchSearchRetrieveInfiniteQueryKey = (params?: SearchSearchRetrieveParams) => {
  return ["infinite", `/search/search/`, ...(params ? [params] : [])] as const;
};

export const getSearchSearchRetrieveQueryKey = (params?: SearchSearchRetrieveParams) => {
  return [`/search/search/`, ...(params ? [params] : [])] as const;
};

export const getSearchSearchRetrieveInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof searchSearchRetrieve>>,
  TError = void,
>(
  params?: SearchSearchRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof searchSearchRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchSearchRetrieveInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSearchRetrieve>>> = ({
    signal,
    pageParam,
  }) =>
    searchSearchRetrieve(
      { ...params, page: pageParam || params?.["page"] },
      requestOptions,
      signal
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof searchSearchRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchSearchRetrieveInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchSearchRetrieve>>
>;
export type SearchSearchRetrieveInfiniteQueryError = void;

export function useSearchSearchRetrieveInfinite<
  TData = Awaited<ReturnType<typeof searchSearchRetrieve>>,
  TError = void,
>(
  params?: SearchSearchRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof searchSearchRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchSearchRetrieveInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSearchSearchRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof searchSearchRetrieve>>,
  TError = void,
>(
  params?: SearchSearchRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof searchSearchRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchSearchRetrieveQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSearchRetrieve>>> = ({ signal }) =>
    searchSearchRetrieve(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchSearchRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchSearchRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchSearchRetrieve>>
>;
export type SearchSearchRetrieveQueryError = void;

export function useSearchSearchRetrieve<
  TData = Awaited<ReturnType<typeof searchSearchRetrieve>>,
  TError = void,
>(
  params?: SearchSearchRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof searchSearchRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchSearchRetrieveQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const searchSuggestionRetrieve = (
  params?: SearchSuggestionRetrieveParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<SearchSuggestionResponse>(
    { url: `/search/suggestion/`, method: "GET", params, signal },
    options
  );
};

export const getSearchSuggestionRetrieveInfiniteQueryKey = (
  params?: SearchSuggestionRetrieveParams
) => {
  return ["infinite", `/search/suggestion/`, ...(params ? [params] : [])] as const;
};

export const getSearchSuggestionRetrieveQueryKey = (params?: SearchSuggestionRetrieveParams) => {
  return [`/search/suggestion/`, ...(params ? [params] : [])] as const;
};

export const getSearchSuggestionRetrieveInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
  TError = unknown,
>(
  params?: SearchSuggestionRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchSuggestionRetrieveInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSuggestionRetrieve>>> = ({
    signal,
    pageParam,
  }) =>
    searchSuggestionRetrieve(
      { ...params, page: pageParam || params?.["page"] },
      requestOptions,
      signal
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchSuggestionRetrieveInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchSuggestionRetrieve>>
>;
export type SearchSuggestionRetrieveInfiniteQueryError = unknown;

export function useSearchSuggestionRetrieveInfinite<
  TData = Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
  TError = unknown,
>(
  params?: SearchSuggestionRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchSuggestionRetrieveInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSearchSuggestionRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
  TError = unknown,
>(
  params?: SearchSuggestionRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof searchSuggestionRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchSuggestionRetrieveQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSuggestionRetrieve>>> = ({
    signal,
  }) => searchSuggestionRetrieve(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchSuggestionRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchSuggestionRetrieve>>
>;
export type SearchSuggestionRetrieveQueryError = unknown;

export function useSearchSuggestionRetrieve<
  TData = Awaited<ReturnType<typeof searchSuggestionRetrieve>>,
  TError = unknown,
>(
  params?: SearchSuggestionRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof searchSuggestionRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchSuggestionRetrieveQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
