/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

export type ApiSchemaRetrieveFormat =
  (typeof ApiSchemaRetrieveFormat)[keyof typeof ApiSchemaRetrieveFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiSchemaRetrieveFormat = {
  json: "json",
  yaml: "yaml",
} as const;
