/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

export type ApiSchemaRetrieveLang =
  (typeof ApiSchemaRetrieveLang)[keyof typeof ApiSchemaRetrieveLang];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiSchemaRetrieveLang = {
  en: "en",
  ru: "ru",
  uz: "uz",
} as const;
