/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ApiSchemaRetrieveFormat } from "./apiSchemaRetrieveFormat";
import type { ApiSchemaRetrieveLang } from "./apiSchemaRetrieveLang";

export type ApiSchemaRetrieveParams = {
  format?: ApiSchemaRetrieveFormat;
  lang?: ApiSchemaRetrieveLang;
};
