/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductIngestResponseStockrecord } from "./productIngestResponseStockrecord";

export interface ProductIngestResponse {
  id: number;
  title: string;
  product_class: string;
  /** @nullable */
  stockrecord?: ProductIngestResponseStockrecord;
}
