/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

export interface ProductImageFromVendorResponse {
  product_id: number;
  image_id: number;
  /** @nullable */
  url?: string | null;
  order: number;
}
