/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductOutputTopChoice } from "./productOutputTopChoice";

export interface ProductOutput {
  readonly title: string;
  readonly description: string;
  /** @maxLength 256 */
  slug: string;
  is_available?: boolean;
  /**
   * @minimum 0
   * @maximum 5
   */
  rating?: number;
  meta_info?: unknown;
  category: number;
  /** @nullable */
  main_image?: number | null;
  readonly top_choice: ProductOutputTopChoice;
  readonly min_price: number;
  readonly variations: number;
}
