/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductIngestRequestAttributes } from "./productIngestRequestAttributes";
import type { StockRecordInRequest } from "./stockRecordInRequest";

export interface ProductIngestRequest {
  /** @minLength 1 */
  title_l0: string;
  /** @nullable */
  title_l1?: string | null;
  /** @nullable */
  title_l2?: string | null;
  /** @nullable */
  description_l0?: string | null;
  /** @nullable */
  description_l1?: string | null;
  /** @nullable */
  description_l2?: string | null;
  /** @minLength 1 */
  name_l0: string;
  /** @nullable */
  name_l1?: string | null;
  /** @nullable */
  name_l2?: string | null;
  /** Either 'Electronics > Phones' or 'electronics/phones'. */
  categories: string[];
  attributes?: ProductIngestRequestAttributes;
  stockrecord: StockRecordInRequest;
  /** @minLength 1 */
  url: string;
  /**
   * @maxLength 128
   * @nullable
   */
  upc?: string | null;
}
