/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `price_mismatch` - Price mismatch
 * `out_of_stock` - Out of stock
 * `wrong_information` - Wrong or misleading information
 * `broken_link` - Broken or invalid link
 * `other` - Other
 */
export type ReasonEnum = (typeof ReasonEnum)[keyof typeof ReasonEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReasonEnum = {
  price_mismatch: "price_mismatch",
  out_of_stock: "out_of_stock",
  wrong_information: "wrong_information",
  broken_link: "broken_link",
  other: "other",
} as const;
