/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductOutput } from "./productOutput";
import type { SearchResultFacets } from "./searchResultFacets";

export interface SearchResult {
  results: ProductOutput[];
  count: number;
  facets?: SearchResultFacets;
}
