/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

export type SearchSearchRetrieveParams = {
  /**
   * Brand filter, repeat for multiple values.
   */
  brand?: string[];
  /**
   * Category filter, repeat for multiple values.
   */
  category?: string[];
  /**
   * Page number (default 1).
   */
  page?: number;
  /**
   * Items per page (default 20).
   */
  page_size?: number;
  /**
   * Maximum price filter.
   */
  price_max?: number;
  /**
   * Minimum price filter.
   */
  price_min?: number;
  /**
   * Search text.
   */
  q?: string;
};
