/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */

export interface StockRecordInRequest {
  /** @minLength 1 */
  partner: string;
  /**
   * @minLength 1
   * @maxLength 12
   */
  currency?: string;
  price: number;
}
