/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ReasonEnum } from "./reasonEnum";

export interface UserReportCreateRequest {
  stockrecord_id: number;
  reason: ReasonEnum;
  /**
   * Required only when reason is 'other'.
   * @maxLength 512
   * @nullable
   */
  other_reason?: string | null;
}
