/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import type { ReasonEnum } from "./reasonEnum";

export interface UserReportResponse {
  readonly id: number;
  stockrecord: number;
  reason: ReasonEnum;
  /**
   * @maxLength 512
   * @nullable
   */
  other_reason?: string | null;
  readonly created_at: string;
}
