/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my project
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiSchemaRetrieve200Four,
  ApiSchemaRetrieve200One,
  ApiSchemaRetrieve200Three,
  ApiSchemaRetrieve200Two,
  ApiSchemaRetrieveParams,
  Error,
  Message,
  ProductImageFromVendorRequest,
  ProductImageFromVendorResponse,
  ProductIngestRequest,
  ProductIngestResponse,
  ProductOutput,
  ProductUpdatePrice,
  ProductUpdatePriceRequest,
  Status,
  StockRecordUpdateAvailability,
  StockRecordUpdateAvailabilityRequest,
  TokenObtainPair,
  TokenObtainPairRequest,
  TokenRefresh,
  TokenRefreshRequest,
  UserReportCreateRequest,
  UserReportResponse,
} from ".././models";

import { customInstance } from ".././mutator/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const apiCatalogueProductRetrieve = (
  productId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ProductOutput>(
    { url: `/api/catalogue/product/${productId}/`, method: "GET", signal },
    options
  );
};

export const getApiCatalogueProductRetrieveInfiniteQueryKey = (productId?: number) => {
  return ["infinite", `/api/catalogue/product/${productId}/`] as const;
};

export const getApiCatalogueProductRetrieveQueryKey = (productId?: number) => {
  return [`/api/catalogue/product/${productId}/`] as const;
};

export const getApiCatalogueProductRetrieveInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiCatalogueProductRetrieveInfiniteQueryKey(productId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>> = ({
    signal,
  }) => apiCatalogueProductRetrieve(productId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!productId, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiCatalogueProductRetrieveInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>
>;
export type ApiCatalogueProductRetrieveInfiniteQueryError = void;

export function useApiCatalogueProductRetrieveInfinite<
  TData = Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiCatalogueProductRetrieveInfiniteQueryOptions(productId, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiCatalogueProductRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiCatalogueProductRetrieveQueryKey(productId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>> = ({
    signal,
  }) => apiCatalogueProductRetrieve(productId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!productId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiCatalogueProductRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>
>;
export type ApiCatalogueProductRetrieveQueryError = void;

export function useApiCatalogueProductRetrieve<
  TData = Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof apiCatalogueProductRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiCatalogueProductRetrieveQueryOptions(productId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiCatalogueProductsAvailableCreate = (
  stockRecordUpdateAvailabilityRequest: StockRecordUpdateAvailabilityRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<StockRecordUpdateAvailability | Status>(
    {
      url: `/api/catalogue/products/available`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: stockRecordUpdateAvailabilityRequest,
      signal,
    },
    options
  );
};

export const getApiCatalogueProductsAvailableCreateMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>,
    TError,
    { data: StockRecordUpdateAvailabilityRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>,
  TError,
  { data: StockRecordUpdateAvailabilityRequest },
  TContext
> => {
  const mutationKey = ["apiCatalogueProductsAvailableCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>,
    { data: StockRecordUpdateAvailabilityRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiCatalogueProductsAvailableCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiCatalogueProductsAvailableCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>
>;
export type ApiCatalogueProductsAvailableCreateMutationBody = StockRecordUpdateAvailabilityRequest;
export type ApiCatalogueProductsAvailableCreateMutationError = Error;

export const useApiCatalogueProductsAvailableCreate = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>,
    TError,
    { data: StockRecordUpdateAvailabilityRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiCatalogueProductsAvailableCreate>>,
  TError,
  { data: StockRecordUpdateAvailabilityRequest },
  TContext
> => {
  const mutationOptions = getApiCatalogueProductsAvailableCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiCatalogueProductsIngestCreate = (
  productIngestRequest: ProductIngestRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Message | ProductIngestResponse>(
    {
      url: `/api/catalogue/products/ingest`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productIngestRequest,
      signal,
    },
    options
  );
};

export const getApiCatalogueProductsIngestCreateMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>,
    TError,
    { data: ProductIngestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>,
  TError,
  { data: ProductIngestRequest },
  TContext
> => {
  const mutationKey = ["apiCatalogueProductsIngestCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>,
    { data: ProductIngestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiCatalogueProductsIngestCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiCatalogueProductsIngestCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>
>;
export type ApiCatalogueProductsIngestCreateMutationBody = ProductIngestRequest;
export type ApiCatalogueProductsIngestCreateMutationError = Error;

export const useApiCatalogueProductsIngestCreate = <TError = Error, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>,
    TError,
    { data: ProductIngestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiCatalogueProductsIngestCreate>>,
  TError,
  { data: ProductIngestRequest },
  TContext
> => {
  const mutationOptions = getApiCatalogueProductsIngestCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiCatalogueProductsPhotosetCreate = (
  productImageFromVendorRequest: ProductImageFromVendorRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ProductImageFromVendorResponse>(
    {
      url: `/api/catalogue/products/photoset`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productImageFromVendorRequest,
      signal,
    },
    options
  );
};

export const getApiCatalogueProductsPhotosetCreateMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>,
    TError,
    { data: ProductImageFromVendorRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>,
  TError,
  { data: ProductImageFromVendorRequest },
  TContext
> => {
  const mutationKey = ["apiCatalogueProductsPhotosetCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>,
    { data: ProductImageFromVendorRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiCatalogueProductsPhotosetCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiCatalogueProductsPhotosetCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>
>;
export type ApiCatalogueProductsPhotosetCreateMutationBody = ProductImageFromVendorRequest;
export type ApiCatalogueProductsPhotosetCreateMutationError = Error | void;

export const useApiCatalogueProductsPhotosetCreate = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>,
    TError,
    { data: ProductImageFromVendorRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiCatalogueProductsPhotosetCreate>>,
  TError,
  { data: ProductImageFromVendorRequest },
  TContext
> => {
  const mutationOptions = getApiCatalogueProductsPhotosetCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiCatalogueProductsUpdatepriceCreate = (
  productUpdatePriceRequest: ProductUpdatePriceRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ProductUpdatePrice | Status>(
    {
      url: `/api/catalogue/products/updateprice`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: productUpdatePriceRequest,
      signal,
    },
    options
  );
};

export const getApiCatalogueProductsUpdatepriceCreateMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>,
    TError,
    { data: ProductUpdatePriceRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>,
  TError,
  { data: ProductUpdatePriceRequest },
  TContext
> => {
  const mutationKey = ["apiCatalogueProductsUpdatepriceCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>,
    { data: ProductUpdatePriceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiCatalogueProductsUpdatepriceCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiCatalogueProductsUpdatepriceCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>
>;
export type ApiCatalogueProductsUpdatepriceCreateMutationBody = ProductUpdatePriceRequest;
export type ApiCatalogueProductsUpdatepriceCreateMutationError = Error;

export const useApiCatalogueProductsUpdatepriceCreate = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>,
    TError,
    { data: ProductUpdatePriceRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiCatalogueProductsUpdatepriceCreate>>,
  TError,
  { data: ProductUpdatePriceRequest },
  TContext
> => {
  const mutationOptions = getApiCatalogueProductsUpdatepriceCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Allow end users to report issues with a StockRecord.
 */
export const apiPartnerStockrecordsReportCreate = (
  userReportCreateRequest: UserReportCreateRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserReportResponse>(
    {
      url: `/api/partner/stockrecords/report`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userReportCreateRequest,
      signal,
    },
    options
  );
};

export const getApiPartnerStockrecordsReportCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>,
    TError,
    { data: UserReportCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>,
  TError,
  { data: UserReportCreateRequest },
  TContext
> => {
  const mutationKey = ["apiPartnerStockrecordsReportCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>,
    { data: UserReportCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiPartnerStockrecordsReportCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiPartnerStockrecordsReportCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>
>;
export type ApiPartnerStockrecordsReportCreateMutationBody = UserReportCreateRequest;
export type ApiPartnerStockrecordsReportCreateMutationError = void;

export const useApiPartnerStockrecordsReportCreate = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>,
    TError,
    { data: UserReportCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiPartnerStockrecordsReportCreate>>,
  TError,
  { data: UserReportCreateRequest },
  TContext
> => {
  const mutationOptions = getApiPartnerStockrecordsReportCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.

- YAML: application/vnd.oai.openapi
- JSON: application/vnd.oai.openapi+json
 */
export const apiSchemaRetrieve = (
  params?: ApiSchemaRetrieveParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<
    | ApiSchemaRetrieve200One
    | ApiSchemaRetrieve200Two
    | ApiSchemaRetrieve200Three
    | ApiSchemaRetrieve200Four
  >({ url: `/api/schema/`, method: "GET", params, signal }, options);
};

export const getApiSchemaRetrieveInfiniteQueryKey = (params?: ApiSchemaRetrieveParams) => {
  return ["infinite", `/api/schema/`, ...(params ? [params] : [])] as const;
};

export const getApiSchemaRetrieveQueryKey = (params?: ApiSchemaRetrieveParams) => {
  return [`/api/schema/`, ...(params ? [params] : [])] as const;
};

export const getApiSchemaRetrieveInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof apiSchemaRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiSchemaRetrieveInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiSchemaRetrieve>>> = ({
    signal,
    pageParam,
  }) =>
    apiSchemaRetrieve({ ...params, page: pageParam || params?.["page"] }, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof apiSchemaRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiSchemaRetrieveInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiSchemaRetrieve>>
>;
export type ApiSchemaRetrieveInfiniteQueryError = unknown;

export function useApiSchemaRetrieveInfinite<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof apiSchemaRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiSchemaRetrieveInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiSchemaRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof apiSchemaRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiSchemaRetrieveQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiSchemaRetrieve>>> = ({ signal }) =>
    apiSchemaRetrieve(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiSchemaRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiSchemaRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiSchemaRetrieve>>
>;
export type ApiSchemaRetrieveQueryError = unknown;

export function useApiSchemaRetrieve<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof apiSchemaRetrieve>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiSchemaRetrieveQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const apiTokenCreate = (
  tokenObtainPairRequest: TokenObtainPairRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<TokenObtainPair>(
    {
      url: `/api/token/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: tokenObtainPairRequest,
      signal,
    },
    options
  );
};

export const getApiTokenCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTokenCreate>>,
    TError,
    { data: TokenObtainPairRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiTokenCreate>>,
  TError,
  { data: TokenObtainPairRequest },
  TContext
> => {
  const mutationKey = ["apiTokenCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiTokenCreate>>,
    { data: TokenObtainPairRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiTokenCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiTokenCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiTokenCreate>>>;
export type ApiTokenCreateMutationBody = TokenObtainPairRequest;
export type ApiTokenCreateMutationError = unknown;

export const useApiTokenCreate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTokenCreate>>,
    TError,
    { data: TokenObtainPairRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiTokenCreate>>,
  TError,
  { data: TokenObtainPairRequest },
  TContext
> => {
  const mutationOptions = getApiTokenCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const apiTokenRefreshCreate = (
  tokenRefreshRequest: TokenRefreshRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<TokenRefresh>(
    {
      url: `/api/token/refresh/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: tokenRefreshRequest,
      signal,
    },
    options
  );
};

export const getApiTokenRefreshCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTokenRefreshCreate>>,
    TError,
    { data: TokenRefreshRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiTokenRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationKey = ["apiTokenRefreshCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiTokenRefreshCreate>>,
    { data: TokenRefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return apiTokenRefreshCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiTokenRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiTokenRefreshCreate>>
>;
export type ApiTokenRefreshCreateMutationBody = TokenRefreshRequest;
export type ApiTokenRefreshCreateMutationError = unknown;

export const useApiTokenRefreshCreate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTokenRefreshCreate>>,
    TError,
    { data: TokenRefreshRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiTokenRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationOptions = getApiTokenRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
